### ISSUE TITLE
support of bundled xk6-browser

### ISSUE THREAD

**Issue by olegchorny** [grafana/k6-action#14]
Hello k6! I wonder if github action is supposed to run a test without a requirement to install the xk6-browser. 

`Uncaught (in promise) GoError: launching browser: exec: no command\n\tat github.com/grafana/xk6-browser/browser.mapBrowserType.func1 `

Thanks!

**Comment by olegchorny** [comment]
Perhaps https://hub.docker.com/layers/loadimpact/k6/latest should be updated?

**Comment by mdcruz** [comment]
Hi @olegchorny!

Can you send us a reproducible step so we can investigate more? Currently, we don't have a k6 docker image yet which contains a browser, so this might be the reason your test is failing. See https://github.com/grafana/k6/issues/2914 for more information.

**Comment by olegchorny** [comment]
> Hi @olegchorny!
> 
> Can you send us a reproducible step so we can investigate more? Currently, we don't have a k6 docker image yet which contains a browser, so this might be the reason your test is failing. See [grafana/k6#2914](https://github.com/grafana/k6/issues/2914) for more information.

right, I managed to setup the job by installing the required bits and invoke k6 run command. Thanks!

**Comment by ppcano** [comment]
> I wonder if github action is supposed to run a test without a requirement to install the xk6-browser.

I think so!

For reference while we wait for the implementation, you can download k6 and enable the required settings to trigger browser tests as shown in this [example](https://github.com/grafana/quickpizza/blob/main/.github/workflows/k6-tests.yaml).

**Comment by ppcano** [comment]
This is now supported in the new GitHub action: https://github.com/grafana/setup-k6-action (`browser`: true)
